// <auto-generated />
using System;
using ComputerStoreFinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComputerStoreFinalProject.Migrations
{
    [DbContext(typeof(ComputerStoreDbContext))]
    [Migration("20220618204531_seedComputerTable")]
    partial class seedComputerTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComputerStoreFinalProject.Models.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Country")
                        .HasColumnType("int")
                        .HasMaxLength(100);

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("ID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ComputerStoreFinalProject.Models.Computer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Computers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyName = "Hp",
                            Model = "notebook 360",
                            Price = 899.99m,
                            Year = 2019
                        },
                        new
                        {
                            ID = 2,
                            CompanyName = "Dell",
                            Model = "Latitude 7420",
                            Price = 2029.00m,
                            Year = 2022
                        },
                        new
                        {
                            ID = 3,
                            CompanyName = "Apple",
                            Model = "MacBook Pro",
                            Price = 3499.00m,
                            Year = 2021
                        },
                        new
                        {
                            ID = 4,
                            CompanyName = "Asus",
                            Model = "Zenbook Duo",
                            Price = 2299.00m,
                            Year = 2022
                        },
                        new
                        {
                            ID = 5,
                            CompanyName = " Asus",
                            Model = "VivoBook Flip",
                            Price = 269.00m,
                            Year = 2022
                        },
                        new
                        {
                            ID = 6,
                            CompanyName = "Dell",
                            Model = "Vostro 3510",
                            Price = 629.00m,
                            Year = 2022
                        },
                        new
                        {
                            ID = 7,
                            CompanyName = "Hp",
                            Model = "Omen",
                            Price = 2349.99m,
                            Year = 2021
                        },
                        new
                        {
                            ID = 8,
                            CompanyName = "Apple",
                            Model = "MacBook Air",
                            Price = 1199.00m,
                            Year = 2022
                        });
                });

            modelBuilder.Entity("ComputerStoreFinalProject.Models.ComputerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComputerID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComputerID");

                    b.HasIndex("OrderID");

                    b.ToTable("ComputerOrders");
                });

            modelBuilder.Entity("ComputerStoreFinalProject.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ComputerStoreFinalProject.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ComputerStoreFinalProject.Models.ComputerOrder", b =>
                {
                    b.HasOne("ComputerStoreFinalProject.Models.Computer", "Computer")
                        .WithMany("ComputerOrder")
                        .HasForeignKey("ComputerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerStoreFinalProject.Models.Order", "Order")
                        .WithMany("ComputerOrder")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComputerStoreFinalProject.Models.Order", b =>
                {
                    b.HasOne("ComputerStoreFinalProject.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
